<?php /* Information about updates, gathered from the author's web site. */ ?>
<?php /* It will be shown as a bar on top of each page in the admin panel. */ ?>
<?php if ($updateInfo = $this->getUpdateInfo()) : ?>
    <div class="notification-global"><?php echo $this->__('UBB Updates:'); ?> <?php echo $updateInfo ?></div>
<?php endif; ?>

<?php /* Important news, gathered from the author's web site. */ ?>
<?php /* They will be shown as separate bars on top of each page in the admin panel. */ ?>
<?php /* If they are not set to be permanent, you will see them only for 1 hour. */ ?>
<?php if ($importantNews = $this->getNews('important')) : ?>
    <?php foreach($importantNews as $impoNews): ?>
        <div class="notification-global notification-global-important">
            <b><?php echo $impoNews['title']; ?></b>
            <?php echo $impoNews['msg']; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php /* Informational news, gathered from the author's web site. */ ?>
<?php /* They will be shown as separate bars on top of each page in the admin panel. */ ?>
<?php /* If they are not set to be permanent, you will see them only for 1 hour. */ ?>
<?php if ($informationalNews = $this->getNews('information')) : ?>
    <?php foreach($informationalNews as $infoNews): ?>
        <div class="notification-global notification-global-notice">
            <b><?php echo $infoNews['title']; ?></b>
            <?php echo $infoNews['msg']; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php /* RIZN-modified pop-up, which shows information only about updates. */ ?>
<?php /* It will be shown once for a session. */ ?>
<?php if($this->showNotif()): ?>
<?php if ($popUp = $this->getUpdateInfo()) : ?>
    <script type="text/javascript">
//<![CDATA[
    var messagePopupClosed = false;
    function openMessagePopup() {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height+'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
        $('message-popup-window').addClassName('show');
    }

    function closeMessagePopup() {
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Element.hide('message-popup-window-mask');
        $('message-popup-window').removeClassName('show');
        messagePopupClosed = true;
    }

    Event.observe(window, 'load', openMessagePopup);
    Event.observe(window, 'keyup', function(evt) {
        if(messagePopupClosed) return;
        var code;
        if (evt.keyCode) code = evt.keyCode;
        else if (evt.which) code = evt.which;
        if (code == Event.KEY_ESC) {
            closeMessagePopup();
        }
    });
//]]>
    </script>
    <div id="message-popup-window-mask"></div>
    <div id="message-popup-window" class="message-popup">
        <div class="message-popup-head">
            <a href="#" onclick="closeMessagePopup(); return false;" title="Close"><span><?php echo $this->__('Close'); ?></span></a>
            <h2><?php echo $this->__('RIZN UBB Updates'); ?></h2>
        </div>
        <div class="message-popup-content">
            <div class="message">
                <img src="<?php echo $this->authorWebSite ?>/rz-ubb-vpos/logo.png"/>
                <p class="message-text" style="width: 264px;"><?php echo $popUp ?></p>
            </div>
            <p class="read-more"></p>
        </div>
    </div>
<?php endif; ?>
<?php endif; ?>

<?php /* Send data to the author in order to make sure that you are using the newest module. */ ?>
<?php if($this->notifyRZ()): ?>
<?php $this->doNotifyRZ(); ?>
<?php endif; ?>
